isi_blnj = input('Masukan 5 barang yang mau kamu beli (pisahkan dengan "," untuk tiap barang): ').lower()
belanja = list(isi_blnj.split(','))
print('Ini adalah daftar yang kamu buat:')
print(belanja)
hps_blnj = input('Hapus satu barang yang sudah kamu beli: ').lower()
belanja.remove(hps_blnj)
print()
print("Sekarang sisa belanjaan kamu adalah:")
print(belanja)