num1 = input('Masukan angka pertama: ')
num2 = input('Masukan angka ke2: ')
tambah = int(num1) + int(num2)
kurang = int(num1) - int(num2)
kali = int(num1) * int(num2)
bagi = int(num1) / int(num2)
print('Perjumlahan', tambah)
print('Pengurangan', kurang)
print('Perkalian', kali)
print('Pembagian', bagi)